project_id_env: "CROWDIN_PROJECT_ID_WEBSITE"
api_token_env: "CROWDIN_TOKEN"
base_path: "../../website"

preserve_hierarchy: true

files:
  - source: "/en.json"
    translation: "/%locale%.json"
    type: "json"
    # update_option: "update_as_unapproved"
