project_id_env: "CROWDIN_PROJECT_ID_LANG"
api_token_env: "CROWDIN_TOKEN"
base_path: "../.."

preserve_hierarchy: true

files:
  - source: "/en_US.lang"
    translation: "/%locale_with_underscore%.lang"
    type: "properties"
    update_option: "update_as_unapproved"
    escape_special_characters: 0
